version: '3.4'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - "dbdata:/var/lib/postgres/data"

  web-app:
    image: erp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  dbdata: 